### ISSUE TITLE
v2.0.0 - Milestone

### ISSUE THREAD

**Issue by corowne** [corowne/lorekeeper#40]
. | Legend
------------ | -------------
❓ | Unassigned
💬 | Needs discussion
👀 | Under review

**New features/Major updates**
- [ ] Upgrade to Laravel 8 - @corowne
- [ ] Update aliases to accommodate other social media sites - branch `feature/auth-rework` @itinerare
- [ ] Expand range of social media sites usable for aliases - @corowne

**Minor changes**
Pending

**Bug fixes**
- [ ]  Users with long usernames cause the sidebar to partially disappear #38
- [ ]  Attempting to edit stock of a store with "free" (cost 0) items errors #26
- [ ]  Users with especially long usernames cannot purchase any/some item(s) from shops #25
- [ ]  MYO submission open/close site setting has no effect, uses design update site setting instead #23

**Comment by itinerare** [comment]
At least on DH, folk that need to upgrade php should give plenty time for that operation to complete before updating (and may want to do it in stages with plenty of time between)
